# Generated by Django 3.2.18 on 2023-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_applicants_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Germany', max_length=255),
        ),
    ]
