# Generated by Django 3.2.18 on 2023-03-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_appliedjobs_savedjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
